format = '''
$cmd_duration

╭─$username@$hostname:$directory$git_branch$nix_shell
╰─[❯❯❯](red) '''

[username]
show_always = true
style_user = 'bold bright-yellow'
style_root = 'bold red'
format = '[$user]($style)'

[hostname]
ssh_only = false
format = '[$ssh_symbol$hostname]($style)'
style = 'bold green'

[directory]
style = 'bold bright-cyan'
truncate_to_repo = false

[git_branch]
symbol = ' '

[nix_shell]
disabled = false
symbol = '❄️'
style = 'bold'
format = 'via [$symbol $name]($style)'

[cmd_duration]
min_time = 1_000
show_notifications = true
min_time_to_notify = 10_000
format = '⏱️ [$duration](black)'
